name: Generated APK AAB (Upload - Create Artifact To Github Action)

env:
  # The main folder containing gradlew
  main_project_module: SeniorProjectDC

  # Android app module inside the main project folder
  android_module: app

  # The name of the Play Store
  playstore_name: testing_store

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Set current date
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set repository name
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      # Set up JDK
      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Make gradlew executable
      - name: Change wrapper permissions
        run: chmod +x ${{ env.main_project_module }}/gradlew

      # Run tests
      - name: Run Gradle tests
        run: cd ${{ env.main_project_module }} && ./gradlew test

      # Build project
      - name: Build Gradle project
        run: cd ${{ env.main_project_module }} && ./gradlew build

      # Build APK Release
      - name: Build APK Release
        run: cd ${{ env.main_project_module }} && ./gradlew ${{ env.android_module }}:assembleRelease

      # Build AAB Release
      - name: Build App Bundle Release (AAB)
        run: cd ${{ env.main_project_module }} && ./gradlew ${{ env.android_module }}:bundleRelease

      # Upload APK Release
      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK Release
          path: ${{ env.main_project_module }}/${{ env.android_module }}/build/outputs/apk/release/

      # Upload AAB Release
      - name: Upload AAB Release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - AAB Release
          path: ${{ env.main_project_module }}/${{ env.android_module }}/build/outputs/bundle/release/
